name: Node-CI
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: npm run test
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: d48299dcc6609a944389d4fde3ad1073bdf9b5cb5dcdad90eec555b12c9b0085
        with:
          coverageCommand: make test-coverage
          debug: true
